version: "3.1"
services:
  cakephp:
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile.cakephp
    container_name: cakephp-server
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "8080:80"
      - "443:443"
    # we are depending on the mysql backend
    depends_on:
      - mysql
    # we mount the working dir into the container, handy for development
    volumes:
      - ./lsn:/var/www/html/
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=chian
      - MYSQL_PASSWORD=chian
      - LINE_CHANNEL_ACCESS_TOKEN=3yQQ7ulOzQ8PrxwdcBjsRnvli4KU0oiC6E1CJBfKD2XjcWrOSOS+ddF6FmXKNpwxtgQKWevLf82Eijyf+HtM2whkqtgQqs2lHbAXNgQgQ1GocVy9PxNNLbNSuT1bDyDkC4DBEGjrLAxskF9Q/9xbAAdB04t89/1O/w1cDnyilFU=
      - LINE_CHANNEL_SECRET=a2d927b933f4cb987239f8b4fc056fea

  mysql:
    image: mysql:5.6
    volumes:
      - ./tmp/data/mysql_db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    env_file:
      - mysql.env
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;' --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: chian
      PMA_PASSWORD: chian
    ports:
      - "3030:80"
